export const LOGIN = "AUTH/LOGIN";
export const LOGOUT = "AUTH/LOGOUT";
export const SHOW_ERROR = "AUTH/SHOW_ERROR";
export const HIDE_ERROR = "AUTH/HIDE_ERROR";

export const CHANGE_DATA_SEARCH = "SEARCH/CHANGE_DATA_SEARCH";
export const GET_HOTELS = "SEARCH/GET_HOTELS";

export const ADD_HOTEL = "FAVORITES/ADD_HOTEL";
export const REMOVE_HOTEL = "FAVORITES/REMOVE_HOTEL";
export const RESET_FAVORITES = "FAVORITES/RESET_FAVORITES";

export const SORT_BY_RATING_ASC = "FAVORITES/SORT_BY_RATING_ASC";
export const SORT_BY_RATING_DESC = "FAVORITES/SORT_BY_RATING_DESC";
export const SORT_BY_RATING_DEFAULT = "FAVORITES/SORT_BY_RATING_DEFAULT";

export const SORT_BY_PRICE_ASC = "FAVORITES/SORT_BY_PRICE_ASC";
export const SORT_BY_PRICE_DESC = "FAVORITES/SORT_BY_PRICE_DESC";
export const SORT_BY_PRICE_DEFAULT = "FAVORITES/SORT_BY_PRICE_DEFAULT";

export const LOADING_ACTIVE = "APP/LOADING_ACTIVE";
export const LOADING_DISABLE = "APP/LOADING_DISABLE";
